spring:
  datasource:
    hikari:
      maximumPoolSize: 1
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.10.2.95:1521:devjfbsm
    username: appl
    password: appl
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

  output:
    ansi:
      enabled: DETECT
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: oracle